version: "3.9"

services:
  laravel-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: laravel-app-dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mariadb
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mariadb

volumes:
  mariadb_data:
